# Home task: pandas 

## Question 1

- Load the energy data from the file [Energy Indicators.xls](http://unstats.un.org/unsd/environment/excel_file_tables/2013/Energy%20Indicators.xls).
It is a list of indicators of energy supply and renewable electricity production from the United Nations for the year 2013.


- It should be put into a DataFrame with the variable name of "energy"


- Make sure to exclude the footer and header information from the datafile.


- The first two columns are unneccessary, so you should get rid of them, and you should change the column labels so that the columns are:<br>
`['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']`


- Convert `Energy Supply` to gigajoules (there are 1,000,000 gigajoules in a petajoule).


- For all countries which have missing data (e.g. data with `...`) make sure this is reflected as `np.NaN` values.


- Rename the following list of countries (for use in later questions):
    - `Republic of Korea`: `South Korea`,
    - `United States of America`: `United States`,
    - `United Kingdom of Great Britain and Northern Ireland`: `United Kingdom`,
    - `China, Hong Kong Special Administrative Region`: `Hong Kong`


- There are also several countries with numbers and/or parenthesis in their name. Be sure to remove these, e.g.:
    - `Bolivia (Plurinational State of)` should be `Bolivia`,
    - `Switzerland17` should be `Switzerland`.


- Next, load the GDP data from the file ["world_bank.csv"](http://data.worldbank.org/indicator/NY.GDP.MKTP.CD). 
It is a csv containing countries' GDP from 1960 to 2015 from World Bank. Call this DataFrame "GDP"


- Make sure to skip the header, and rename the following list of countries:
    - `Korea, Rep.`: `South Korea`,
    - `Iran, Islamic Rep.`: `Iran`,
    - `Hong Kong SAR, China`: `Hong Kong`


- Finally, load the "Sciamgo Journal and Country Rank data for [Energy Engineering and Power Technology"](http://www.scimagojr.com/countryrank.php?category=2102). It ranks countries based on their journal contributions in the aforementioned area. Call this DataFrame "ScimEn"


- Join the three datasets: Energy, GDP, and ScimEn into a new dataset (using the intersection of country names). Use only the 10 years (2006-2015) of GDP data and only the top 15 countries by Scimagojr 'Rank' (Rank 1 through 15).


- The index of this DataFrame should be the name of the country, and the columns should be<br>
`['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations', 'Citations per document', 'H index', 'Energy Supply', 'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008', '2009', '2010', '2011', 2012', '2013', '2014', '2015']`

Function "answer_one" should return the resulted DataFrame (20 columns and 15 entries)

In [4]:
import pandas as pd
import numpy as np

  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'c:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting pandas
  Downloading pandas-3.0.2-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy
  Downloading numpy-2.4.4-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Collecting xlrd
  Downloading xlrd-2.0.2-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.9 MB 1.7 MB/s eta 0:00:06
   ----- ---------------------------------- 1.3/9.9 MB 2.2 MB/s eta 0:00:04
   ------- -------------------------------- 1.8/9.9 MB 2.4 MB/s eta 0:00:04
   ------- -------------------------------- 1.8/9.9 MB 2.4 MB/s eta 0:00:04
   ------- -------------------------------- 1.8/9.9 MB 2.4 MB/s eta 0:00:04
   -------- ------------------------------- 2.1/9.9 MB 1.3 MB/s eta 0:00:06
   -------- ------------------------------- 2.1/9.9 MB 1.3 MB/s eta 0:00:06
   --------- ------------------------------ 2.4/9.9 MB 1.2 MB/s eta 0:00:07
   --------- ------------------------------ 2.4/9.9 MB 1.2 MB/s eta 0:00:07
   --------- ------------------------------ 2.4/9.9 MB 1.2 MB/s eta 0:00:07
   ----------- ---------------------------- 2.9/9.9 MB 1.1 MB/s eta 0:00:07
   ------------ --------------------------- 3.1/9.9 MB 1.1 MB/s eta 0:00:07
   ------------- -------------------------- 3.4/9.9 MB 1.1 MB/s eta 0:00:06
   ------------- -------------------------- 3.4/9.9 MB 1.1 MB/s eta 0:00:06
   ------------- -------------------------- 3.4/9.9 MB 1.1 MB/s eta 0:00:06
   ------------- -------------------------- 3.4/9.9 MB 1.1 MB/s eta 0:00:06
   -------------- ------------------------- 3.7/9.9 MB 927.3 kB/s eta 0:00:07
   -------------- ------------------------- 3.7/9.9 MB 927.3 kB/s eta 0:00:07
   ----------------- ---------------------- 4.2/9.9 MB 962.3 kB/s eta 0:00:06
   ------------------ --------------------- 4.5/9.9 MB 967.5 kB/s eta 0:00:06
   --------------------- ------------------ 5.2/9.9 MB 1.1 MB/s eta 0:00:05
   ---------------------- ----------------- 5.5/9.9 MB 1.1 MB/s eta 0:00:04
   ----------------------- ---------------- 5.8/9.9 MB 1.1 MB/s eta 0:00:04
   ----------------------- ---------------- 5.8/9.9 MB 1.1 MB/s eta 0:00:04
   ------------------------ --------------- 6.0/9.9 MB 1.1 MB/s eta 0:00:04
   -------------------------- ------------- 6.6/9.9 MB 1.1 MB/s eta 0:00:03
   -------------------------- ------------- 6.6/9.9 MB 1.1 MB/s eta 0:00:03
   --------------------------- ------------ 6.8/9.9 MB 1.1 MB/s eta 0:00:03
   ---------------------------- ----------- 7.1/9.9 MB 1.1 MB/s eta 0:00:03
   ----------------------------- ---------- 7.3/9.9 MB 1.1 MB/s eta 0:00:03
   ----------------------------- ---------- 7.3/9.9 MB 1.1 MB/s eta 0:00:03
   ---------------------------------- ----- 8.4/9.9 MB 1.2 MB/s eta 0:00:02
   ---------------------------------------  9.7/9.9 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 1.3 MB/s  0:00:08
Downloading numpy-2.4.4-cp314-cp314-win_amd64.whl (12.4 MB)
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   --- ------------------------------------ 1.0/12.4 MB 4.8 MB/s eta 0:00:03
   --- ------------------------------------ 1.0/12.4 MB 4.8 MB/s eta 0:00:03
   ----- ---------------------------------- 1.6/12.4 MB 2.2 MB/s eta 0:00:05
   ----- ---------------------------------- 1.8/12.4 MB 2.0 MB/s eta 0:00:06
   ----- ---------------------------------- 1.8/12.4 MB 2.0 MB/s eta 0:00:06
   ------ --------------------------------- 2.1/12.4 MB 1.6 MB/s eta 0:00:07
   ------ --------------------------------- 2.1/12.4 MB 1.6 MB/s eta 0:00:07
   --------- ------------------------------ 2.9/12.4 MB 1.6 MB/s eta 0:00:07
   ---------- ----------------------------- 3.1/12.4 MB 1.6 MB/s eta 0:00:06
   ---------- ----------------------------- 3.1/12.4 MB 1.6 MB/s eta 0:00:06
   ---------- ----------------------------- 3.4/12.4 MB 1.4 MB/s eta 0:00:07
   ----------- ---------------------------- 3.7/12.4 MB 1.3 MB/s eta 0:00:07
   ----------- ---------------------------- 3.7/12.4 MB 1.3 MB/s eta 0:00:07
   ----------- ---------------------------- 3.7/12.4 MB 1.3 MB/s eta 0:00:07
   ----------- ---------------------------- 3.7/12.4 MB 1.3 MB/s eta 0:00:07
   --------------- ------------------------ 4.7/12.4 MB 1.3 MB/s eta 0:00:06
   ----------------- ---------------------- 5.5/12.4 MB 1.5 MB/s eta 0:00:05
   -------------------- ------------------- 6.3/12.4 MB 1.6 MB/s eta 0:00:04
   ---------------------- ----------------- 7.1/12.4 MB 1.7 MB/s eta 0:00:04
   ------------------------- -------------- 7.9/12.4 MB 1.8 MB/s eta 0:00:03
   ------------------------- -------------- 7.9/12.4 MB 1.8 MB/s eta 0:00:03
   ------------------------- -------------- 7.9/12.4 MB 1.8 MB/s eta 0:00:03
   -------------------------- ------------- 8.4/12.4 MB 1.7 MB/s eta 0:00:03
   --------------------------- ------------ 8.7/12.4 MB 1.7 MB/s eta 0:00:03
   ---------------------------- ----------- 8.9/12.4 MB 1.7 MB/s eta 0:00:03
   ---------------------------- ----------- 8.9/12.4 MB 1.7 MB/s eta 0:00:03
   ------------------------------ --------- 9.4/12.4 MB 1.7 MB/s eta 0:00:02
   -------------------------------- ------- 10.2/12.4 MB 1.7 MB/s eta 0:00:02
   ---------------------------------- ----- 10.7/12.4 MB 1.7 MB/s eta 0:00:01
   ------------------------------------ --- 11.3/12.4 MB 1.7 MB/s eta 0:00:01
   ------------------------------------- -- 11.5/12.4 MB 1.7 MB/s eta 0:00:01
   -------------------------------------- - 12.1/12.4 MB 1.8 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.4 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 1.7 MB/s  0:00:07
Downloading xlrd-2.0.2-py2.py3-none-any.whl (96 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: xlrd, tzdata, numpy, et-xmlfile, pandas, openpyxl

   ---------------------------------------- 0/6 [xlrd]
   ---------------------------------------- 0/6 [xlrd]
   ---------------------------------------- 0/6 [xlrd]
   ---------------------------------------- 0/6 [xlrd]
   ------ --------------------------------- 1/6 [tzdata]
   ------ --------------------------------- 1/6 [tzdata]
   ------ --------------------------------- 1/6 [tzdata]
   ------ --------------------------------- 1/6 [tzdata]
   ------ --------------------------------- 1/6 [tzdata]
   ------ --------------------------------- 1/6 [tzdata]
   ------ --------------------------------- 1/6 [tzdata]
   ------ --------------------------------- 1/6 [tzdata]
   ------ --------------------------------- 1/6 [tzdata]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   ------------- -------------------------- 2/6 [numpy]
   -------------------- ------------------- 3/6 [et-xmlfile]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]
   -------------------------- ------------- 4/6 [pandas]

In [19]:
def answer_one():
    energy = pd.read_excel('Energy Indicators.xls', skiprows=17, skipfooter=38)
    energy = energy.drop(energy.columns[[0, 1]], axis=1)
    energy.columns = ['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']
    energy.replace('...', np.nan, inplace=True)
    energy['Energy Supply'] = energy['Energy Supply'] * 1000000
    energy['Country'] = energy['Country'].str.replace(r" \(.*\)", "", regex=True)
    energy['Country'] = energy['Country'].str.replace(r"\d+", "", regex=True)
    energy['Country'] = energy['Country'].replace({
        'Republic of Korea': 'South Korea',
        'United States of America': 'United States',
        'United Kingdom of Great Britain and Northern Ireland': 'United Kingdom',
        'China, Hong Kong Special Administrative Region': 'Hong Kong'
    })
    
    GDP = pd.read_csv('world_bank.csv', skiprows=4)
    GDP['Country Name'] = GDP['Country Name'].replace({
        'Korea, Rep.': 'South Korea',
        'Iran, Islamic Rep.': 'Iran',
        'Hong Kong SAR, China': 'Hong Kong'
    })
    GDP = GDP.rename(columns={'Country Name': 'Country'})
    ScimEn = pd.read_excel('scimagojr country rank 1996-2024.xlsx') 
    ScimEn_top15 = ScimEn[:15]
    gdp_columns = ['Country', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']
    GDP_filtered = GDP[gdp_columns]
    df_merge1 = pd.merge(ScimEn_top15, energy, on='Country', how='inner')
    final_df = pd.merge(df_merge1, GDP_filtered, on='Country', how='inner')
    final_df = final_df.set_index('Country')
    
    return final_df

In [20]:
answer_one()

,Rank,Region,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,...,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,,
China,1,Asiatic Region,472465,470142,6591474,4594673,13.95,380,127191000000,93,...,2.791498e+12,3.604056e+12,4.667346e+12,5.189577e+12,6.192565e+12,7.671757e+12,8.673665e+12,9.743124e+12,1.067453e+13,1.128081e+13
United States,2,Northern America,222772,217929,4131736,1119917,18.55,491,90838000000,286,...,1.381559e+13,1.447423e+13,1.476986e+13,1.447806e+13,1.504896e+13,1.559973e+13,1.625397e+13,1.684319e+13,1.755068e+13,1.820602e+13
India,3,Asiatic Region,96975,94714,1243636,479638,12.82,258,33195000000,26,...,9.402599e+11,1.216736e+12,1.198895e+12,1.341888e+12,1.675616e+12,1.823052e+12,1.827638e+12,1.856722e+12,2.039126e+12,2.103588e+12
United Kingdom,4,Western Europe,61946,60287,1326766,207337,21.42,313,7920000000,124,...,2.719558e+12,3.104700e+12,2.945252e+12,2.429358e+12,2.496741e+12,2.675590e+12,2.719716e+12,2.796908e+12,3.085362e+12,2.945580e+12
Japan,5,Asiatic Region,61939,61307,813472,166907,13.13,246,18984000000,149,...,4.601663e+12,4.579751e+12,5.106679e+12,5.289493e+12,5.759072e+12,6.233147e+12,6.272363e+12,5.212328e+12,4.896994e+12,4.444931e+12
Germany,6,Western Europe,55466,54296,932195,185376,16.81,274,13261000000,165,...,3.046309e+12,3.484057e+12,3.808198e+12,3.478546e+12,3.467094e+12,3.823576e+12,3.596483e+12,3.807024e+12,3.964871e+12,3.425100e+12
Russian Federation,7,Eastern Europe,49938,49562,268391,112125,5.37,123,30709000000,214,...,9.899321e+11,1.299703e+12,1.660848e+12,1.222646e+12,1.524917e+12,2.045923e+12,2.208294e+12,2.292470e+12,2.059242e+12,1.363482e+12
Canada,8,Northern America,44877,44004,1082361,161133,24.12,305,10431000000,296,...,1.319265e+12,1.468820e+12,1.552990e+12,1.374625e+12,1.617343e+12,1.793327e+12,1.828366e+12,1.846597e+12,1.805750e+12,1.556509e+12
Italy,9,Western Europe,42635,40695,767280,171442,18.00,227,6530000000,109,...,1.958564e+12,2.222524e+12,2.417508e+12,2.209484e+12,2.144936e+12,2.306974e+12,2.097929e+12,2.153226e+12,2.173256e+12,1.845428e+12
South Korea,10,Asiatic Region,42534,42174,761076,124789,17.89,215,11007000000,221,...,1.095176e+12,1.220912e+12,1.091581e+12,9.830652e+11,1.192830e+12,1.307103e+12,1.335344e+12,1.434670e+12,1.556252e+12,1.539212e+12
Iran,11,Middle East,35889,35484,798505,211983,22.25,218,9172000000,119,...,2.656022e+11,3.497366e+11,4.060709e+11,4.140591e+11,4.870696e+11,6.290823e+11,6.440193e+11,5.003998e+11,4.622848e+11,4.091917e+11
France,12,Western Europe,33407,32698,637552,99244,19.08,235,10597000000,166,...,2.317862e+12,2.655817e+12,2.926803e+12,2.700076e+12,2.646230e+12,2.870409e+12,2.683007e+12,2.816078e+12,2.861236e+12,2.442483e+12
Spain,13,Western Europe,32521,31781,726414,118758,22.34,233,4923000000,106,...,1.261847e+12,1.476746e+12,1.636115e+12,1.496588e+12,1.427989e+12,1.487569e+12,1.330995e+12,1.362187e+12,1.380245e+12,1.206165e+12
Australia,14,Pacific Region,31047,30232,760284,99637,24.49,262,5386000000,231,...,7.497084e+11,8.566036e+11,1.058448e+12,9.317617e+11,1.152567e+12,1.402940e+12,1.552728e+12,1.583737e+12,1.474677e+12,1.356806e+12
Brazil,15,Latin America,30840,30383,371926,84223,12.06,167,12149000000,59,...,1.107627e+12,1.397114e+12,1.695855e+12,1.666996e+12,2.208838e+12,2.616157e+12,2.465228e+12,2.472819e+12,2.456044e+12,1.802212e+12

## Answer the following questions in the context of only the top 15 countries by Scimagojr Rank (aka the DataFrame returned by `answer_one()`)

### Question 2
What is the average GDP over the last 10 years for each country? (exclude missing values from this calculation.)

*This function should return a Series named `avgGDP` with 15 countries and their average GDP sorted in descending order.*

In [21]:
def answer_two():
    Top15 = answer_one()
    years = ['2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']
    avgGDP = Top15[years].mean(axis=1)
    avgGDP = avgGDP.sort_values(ascending=False)
    avgGDP.name = 'avgGDP'
    return avgGDP

In [22]:
answer_two()

Country
United States         1.570403e+13
China                 7.048894e+12
Japan                 5.239642e+12
Germany               3.590126e+12
United Kingdom        2.791877e+12
France                2.692000e+12
Italy                 2.152983e+12
Brazil                1.988889e+12
Russian Federation    1.666746e+12
Canada                1.616359e+12
India                 1.602352e+12
Spain                 1.406644e+12
South Korea           1.275614e+12
Australia             1.211998e+12
Iran                  4.567516e+11
Name: avgGDP, dtype: float64

### Question 3
By how much had the GDP changed over the 10 year span for the country with the 6th largest average GDP?

*This function should return a single number.*

In [ ]:
def answer_three():
    Top15 = answer_one()
    avgGDP = answer_two()
    country_6th = avgGDP.index[5]
    target_country = Top15.loc[country_6th]
    change = target_country['2015'] - target_country['2006']
    return change

In [25]:
answer_three()

np.float64(124621907951.68018)

### Question 4

Create a new column that is the ratio of Self-Citations to Total Citations. 
What is the maximum value for this new column, and what country has the highest ratio?

*This function should return a tuple with the name of the country and the ratio.*

In [26]:
def answer_four():
    Top15 = answer_one()
    ratio = Top15['Self-citations'] / Top15['Citations']
    max_country = ratio.idxmax()
    max_ratio = ratio.max()
    return (max_country, max_ratio)

In [27]:
answer_four()

('China', np.float64(0.6970630544852335))

### Question 5

Create a column that estimates the population using Energy Supply and Energy Supply per capita. 
What is the third most populous country according to this estimate?

*This function should return a single string value.*

In [ ]:
def answer_five():
    Top15 = answer_one()
    Top15['Population'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    top_pop_countries = Top15['Population'].sort_values(ascending=False)
    return top_pop_countries.index[2]

In [29]:
answer_five()

'United States'

### Question 6
Create a column that estimates the number of citable documents per person. 
What is the correlation between the number of citable documents per capita and the energy supply per capita? Use the `.corr()` method, (Pearson's correlation).

*This function should return a single number.*

In [30]:
def answer_six():
    Top15 = answer_one()
    Top15['PopEst'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    Top15['Citable docs per Capita'] = Top15['Citable documents'] / Top15['PopEst']
    correlation = Top15['Citable docs per Capita'].corr(Top15['Energy Supply per Capita'])
    return correlation

In [31]:
answer_six()

np.float64(0.6905473831164103)

### Question 7
Use the following dictionary to group the Countries by Continent, then create a dateframe that displays the sample size (the number of countries in each continent bin), and the sum, mean, and std deviation for the estimated population of each country.

```python
ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}
```

*This function should return a DataFrame with index named Continent `['Asia', 'Australia', 'Europe', 'North America', 'South America']` and columns `['size', 'sum', 'mean', 'std']`*

In [32]:
def answer_seven():
    Top15 = answer_one()
    ContinentDict  = {'China':'Asia', 'United States':'North America', 'Japan':'Asia', 
                      'United Kingdom':'Europe', 'Russian Federation':'Europe', 
                      'Canada':'North America', 'Germany':'Europe', 'India':'Asia',
                      'France':'Europe', 'South Korea':'Asia', 'Italy':'Europe', 
                      'Spain':'Europe', 'Iran':'Asia', 'Australia':'Australia', 
                      'Brazil':'South America'}
    Top15['PopEst'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    Top15['Continent'] = [ContinentDict[country] for country in Top15.index]
    result = Top15.groupby('Continent')['PopEst'].agg(['size', 'sum', 'mean', 'std'])
    return result

In [33]:
answer_seven()

               size               sum              mean           std
Continent
Asia              5   2898666386.6106   579733277.32212  6.790979e+08
Australia         1   23316017.316017   23316017.316017           NaN
Europe            6  457929667.216372   76321611.202729  3.464767e+07
North America     2   352855249.48025  176427624.740125  1.996696e+08
South America     1  205915254.237288  205915254.237288           NaN